### ISSUE TITLE
Depending on r-arrow makes environment solving very slow

### ISSUE THREAD

**Issue by hechth** [conda-forge/r-arrow-feedstock#59]
### Comment:

When creating environments that contain the r-arrow package, resolving the environment becomes so much slower.

```yaml
name: test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-arrow
```
With arrow:
real    6m9.544s
user    5m58.055s
sys     0m8.424s

Without:
real    1m5.540s
user    0m59.312s
sys     0m2.979s

In a realistic environment

```yaml
name: test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-mass
  - r-rgl
  - bioconductor-mzR
  - r-splines2
  - r-doparallel
  - r-foreach
  - r-snow
  - r-rcpp
  - r-arrow
  - r-dplyr
  - r-tidyr
  - r-stringr
  - r-tibble
```
With:
real    10m21.143s
user    10m3.867s
sys     0m10.864s

Without:
real    1m47.504s
user    1m36.976s
sys     0m4.236s
